# Generated by Django 5.0.4 on 2024-04-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=250)),
                ('time', models.TimeField()),
                ('period', models.CharField(choices=[('EVERYDAY', 'everyday'), ('TWO_DAYS', 'two_days'), ('THREE_DAYS', 'three_days')], default='EVERYDAY', max_length=10)),
                ('duration', models.PositiveIntegerField(default=10)),
                ('is_public', models.BooleanField(default=False)),
                ('gift', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NiceHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=250)),
                ('time', models.TimeField()),
                ('period', models.CharField(choices=[('EVERYDAY', 'everyday'), ('TWO_DAYS', 'two_days'), ('THREE_DAYS', 'three_days')], default='EVERYDAY', max_length=10)),
                ('duration', models.PositiveIntegerField(default=10)),
                ('is_public', models.BooleanField(default=False)),
                ('is_nice', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
